apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: payee-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: redis-secret
        key: redisHost
    - name: redisPassword
      secretKeyRef:
        name: redis-secret
        key: redisPassword
auth:
  secretStore: local-secret-store
